### ISSUE TITLE
Behavior not coherent with git docs

### ISSUE THREAD

**Issue by jairbubbles** [markashleybell/MAB.DotIgnore#21] opened 2020-09-23 16:04 UTC
Hello,

When looking at examples on https://git-scm.com/docs/gitignore#_examples and more precisely:

> The pattern "foo/*", matches "foo/test.json" (a regular file), "foo/bar" (a directory), but it does not match "foo/bar/hello.c" (a regular file), as the asterisk in the pattern does not match "bar/hello.c" which has a slash in it.

I noticed it's not working properly with that lib, `foo/bar/hello.c` will be considered ignored.

```csharp
[Test]
public void Test_git_example()
{
    var ignoreList = new IgnoreList( new[] {"foo/*"});
    Assert.IsTrue(ignoreList.IsIgnored("foo/bar", pathIsDirectory: true));
    Assert.IsTrue(ignoreList.IsIgnored("foo/test.json", pathIsDirectory: false));
    Assert.IsFalse(ignoreList.IsIgnored("foo/bar/hello.c", pathIsDirectory: false)); // Fails here
}
```

**Comment by markashleybell** [comment] 2020-09-24 07:34
Thanks, I'll look into it when I get a sec!

**Comment by jairbubbles** [comment] 2020-09-28 09:30
I investigated a bit more and weirdly even if the doc says so I didn't get the mentioned behavior with `git.exe` 

To only ignore files in a folder (and not subfolders) I had to use: `/foo/*.*' (which will not work with files with no extension)

**Comment by markashleybell** [comment] 2020-09-28 13:23
Interesting! After looking into it a bit, in fact the `IgnoreRule` implementation does work as expected; the issue is with the way `IgnoreList` works out if any of a file's parent directories are ignored ([see here for my intended fix](https://github.com/markashleybell/MAB.DotIgnore/compare/issue-21)).

**Comment by jairbubbles** [comment] 2020-09-28 14:39
Ok but if git does not follow it doc I'm not sure you should ;-)

**Comment by markashleybell** [comment] 2020-10-01 06:37
I'm inclined to agree 🙂 

The goal is to mimic git's behaviour, after all; plus, the fix I've come up with doesn't seem all that robust anyway...

Closing this for now—if others raise it then perhaps we can revisit, but currently the library does behave in the same way as Git (even if that's not correct according to the docs).

**Closed by markashleybell** 2020-10-01 06:37 UTC
Labels: bug

**Comment by jairbubbles** [comment] 2020-10-01 08:29
In that regard, I feel like it would be super cool if all test cases were also tested against the git command line.

**Comment by markashleybell** [comment] 2020-10-01 09:52
Funnily enough, at one point they were (or at least against a standalone compiled version of `wildmatch`): but it was very fragile and hard to get working in CI or cross-platform situations. Would be nice to try and figure it out again, very short of time at the moment though!
